#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Kapicua25.Droid.Resource", IsApplication=true)]

namespace Kapicua25.Droid
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "12.2.4.160")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F010000
			public const int colorAccent = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int colorPrimary = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int colorPrimaryDark = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int ic_launcher_background = 2130771971;
			
			// aapt resource value: 0x7F010004
			public const int launcher_background = 2130771972;
			
			// aapt resource value: 0x7F010005
			public const int splash_background = 2130771973;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F02001C
			public const int add = 2130837532;
			
			// aapt resource value: 0x7F020000
			public const int Ajustes = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int Ajustes24 = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int AndroidSplash7 = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int AndroidSplash8 = 2130837507;
			
			// aapt resource value: 0x7F02001D
			public const int arrow = 2130837533;
			
			// aapt resource value: 0x7F020004
			public const int Ayuda24 = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int Borrar = 2130837509;
			
			// aapt resource value: 0x7F02001E
			public const int delete = 2130837534;
			
			// aapt resource value: 0x7F020006
			public const int Document = 2130837510;
			
			// aapt resource value: 0x7F020020
			public const int documento = 2130837536;
			
			// aapt resource value: 0x7F020021
			public const int documentos = 2130837537;
			
			// aapt resource value: 0x7F02001F
			public const int documentRojo = 2130837535;
			
			// aapt resource value: 0x7F020022
			public const int domino = 2130837538;
			
			// aapt resource value: 0x7F020007
			public const int Equipo1 = 2130837511;
			
			// aapt resource value: 0x7F020008
			public const int Equipo2 = 2130837512;
			
			// aapt resource value: 0x7F020023
			public const int exclamacion = 2130837539;
			
			// aapt resource value: 0x7F020024
			public const int exclamacionRojo = 2130837540;
			
			// aapt resource value: 0x7F020025
			public const int home = 2130837541;
			
			// aapt resource value: 0x7F020026
			public const int home1 = 2130837542;
			
			// aapt resource value: 0x7F020027
			public const int home2 = 2130837543;
			
			// aapt resource value: 0x7F020009
			public const int HOMEICON = 2130837513;
			
			// aapt resource value: 0x7F020028
			public const int homeRojo = 2130837544;
			
			// aapt resource value: 0x7F02000B
			public const int Icon1 = 2130837515;
			
			// aapt resource value: 0x7F02000C
			public const int Icon2 = 2130837516;
			
			// aapt resource value: 0x7F020029
			public const int info = 2130837545;
			
			// aapt resource value: 0x7F02000A
			public const int INFOICON = 2130837514;
			
			// aapt resource value: 0x7F02002A
			public const int instagram = 2130837546;
			
			// aapt resource value: 0x7F02002B
			public const int interrogacion = 2130837547;
			
			// aapt resource value: 0x7F02002C
			public const int interrogacionRojo = 2130837548;
			
			// aapt resource value: 0x7F02000D
			public const int Kapicua250New = 2130837517;
			
			// aapt resource value: 0x7F02000E
			public const int KapicuaRound = 2130837518;
			
			// aapt resource value: 0x7F02002D
			public const int leftarrow = 2130837549;
			
			// aapt resource value: 0x7F02000F
			public const int Logo1024 = 2130837519;
			
			// aapt resource value: 0x7F020010
			public const int Logo250 = 2130837520;
			
			// aapt resource value: 0x7F020011
			public const int Logo512 = 2130837521;
			
			// aapt resource value: 0x7F020012
			public const int LogoKapicua = 2130837522;
			
			// aapt resource value: 0x7F020013
			public const int LogoKapicua2014 = 2130837523;
			
			// aapt resource value: 0x7F020014
			public const int LogoKapicua2014Redondo = 2130837524;
			
			// aapt resource value: 0x7F020016
			public const int Logophoto = 2130837526;
			
			// aapt resource value: 0x7F020015
			public const int Logo_round = 2130837525;
			
			// aapt resource value: 0x7F020017
			public const int NuevoLogoKapicua = 2130837527;
			
			// aapt resource value: 0x7F020018
			public const int PaseRedondo = 2130837528;
			
			// aapt resource value: 0x7F020019
			public const int PaseRedondoBlanco = 2130837529;
			
			// aapt resource value: 0x7F02002E
			public const int pencil = 2130837550;
			
			// aapt resource value: 0x7F02002F
			public const int pencil2 = 2130837551;
			
			// aapt resource value: 0x7F020030
			public const int pencil3 = 2130837552;
			
			// aapt resource value: 0x7F020031
			public const int pencil4 = 2130837553;
			
			// aapt resource value: 0x7F020032
			public const int pencil5 = 2130837554;
			
			// aapt resource value: 0x7F020033
			public const int refresh24 = 2130837555;
			
			// aapt resource value: 0x7F020034
			public const int settings = 2130837556;
			
			// aapt resource value: 0x7F020035
			public const int settingsRojo = 2130837557;
			
			// aapt resource value: 0x7F020036
			public const int share = 2130837558;
			
			// aapt resource value: 0x7F020037
			public const int splash_screen = 2130837559;
			
			// aapt resource value: 0x7F02001A
			public const int Trofeo24 = 2130837530;
			
			// aapt resource value: 0x7F02001B
			public const int Winner = 2130837531;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F030000
			public const int Assets = 2130903040;
			
			// aapt resource value: 0x7F030005
			public const int icon = 2130903045;
			
			// aapt resource value: 0x7F030006
			public const int icon_round = 2130903046;
			
			// aapt resource value: 0x7F030002
			public const int ic_launcher = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int ic_launcher_foreground = 2130903043;
			
			// aapt resource value: 0x7F030004
			public const int ic_launcher_round = 2130903044;
			
			// aapt resource value: 0x7F030001
			public const int Kapicua = 2130903041;
			
			// aapt resource value: 0x7F030007
			public const int launcher_foreground = 2130903047;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F040000
			public const int MainTheme = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int SplashTheme = 2130968577;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
